### Exercici 3
#### creació d'una nova base de dades únicament amb les dades requrides

In [8]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('delayedflights.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1936758 entries, 0 to 1936757
Data columns (total 30 columns):
 #   Column             Dtype
---  ------             -----
 0   Unnamed: 0         int64
 1   Year               int64
 2   Month              int64
 3   DayofMonth         int64
 4   DayOfWeek          int64
 5   DepTime            float64
 6   CRSDepTime         int64
 7   ArrTime            float64
 8   CRSArrTime         int64
 9   UniqueCarrier      object
 10  FlightNum          int64
 11  TailNum            object
 12  ActualElapsedTime  float64
 13  CRSElapsedTime     float64
 14  AirTime            float64
 15  ArrDelay           float64
 16  DepDelay           float64
 17  Origin             object
 18  Dest               object
 19  Distance           int64
 20  TaxiIn             float64
 21  TaxiOut            float64
 22  Cancelled          int64
 23  CancellationCode   object
 24  Diverted           int64
 25  CarrierDelay       float64
 26  WeatherDelay       float64
 27  NASDelay           float64
 28  SecurityDelay      float64
 29  LateAircraftDelay  float64
dtypes: float64(14), int64(11), object(5)
memory usage: 443.3+ MB

In [3]:
dbsimple = df[["Year", "Month", "DayofMonth","UniqueCarrier","ArrDelay","DepDelay","AirTime","Origin","Dest"]]
dbsimple.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1936758 entries, 0 to 1936757
Data columns (total 9 columns):
 #   Column         Dtype
---  ------         -----
 0   Year           int64
 1   Month          int64
 2   DayofMonth     int64
 3   UniqueCarrier  object
 4   ArrDelay       float64
 5   DepDelay       float64
 6   AirTime        float64
 7   Origin         object
 8   Dest           object
dtypes: float64(3), int64(3), object(3)
memory usage: 133.0+ MB

In [4]:
dbsimple.to_csv("dbsimple.csv")

In [5]:
df_nova = pd.read_csv('dbsimple.csv', index_col=[0])
df_nova.info()

/Users/psans/opt/anaconda3/lib/python3.8/site-packages/numpy/lib/arraysetops.py:583: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1936758 entries, 0 to 1936757
Data columns (total 9 columns):
 #   Column         Dtype
---  ------         -----
 0   Year           int64
 1   Month          int64
 2   DayofMonth     int64
 3   UniqueCarrier  object
 4   ArrDelay       float64
 5   DepDelay       float64
 6   AirTime        float64
 7   Origin         object
 8   Dest           object
dtypes: float64(3), int64(3), object(3)
memory usage: 147.8+ MB

In [6]:
df_nova.head(20)

,Year,Month,DayofMonth,UniqueCarrier,ArrDelay,DepDelay,AirTime,Origin,Dest
0,2008,1,3,WN,-14.0,8.0,116.0,IAD,TPA
1,2008,1,3,WN,2.0,19.0,113.0,IAD,TPA
2,2008,1,3,WN,14.0,8.0,76.0,IND,BWI
3,2008,1,3,WN,34.0,34.0,77.0,IND,BWI
4,2008,1,3,WN,11.0,25.0,87.0,IND,JAX
5,2008,1,3,WN,57.0,67.0,230.0,IND,LAS
6,2008,1,3,WN,1.0,6.0,106.0,IND,MCO
7,2008,1,3,WN,80.0,94.0,107.0,IND,MCO
8,2008,1,3,WN,11.0,9.0,37.0,IND,MDW
9,2008,1,3,WN,15.0,27.0,213.0,IND,PHX
10,2008,1,3,WN,-15.0,9.0,205.0,IND,PHX
11,2008,1,3,WN,16.0,28.0,110.0,IND,TPA
12,2008,1,3,WN,37.0,51.0,49.0,ISP,BWI
13,2008,1,3,WN,19.0,32.0,47.0,ISP,BWI
14,2008,1,3,WN,6.0,20.0,49.0,ISP,BWI
15,2008,1,3,WN,-7.0,9.0,47.0,ISP,BWI
16,2008,1,3,WN,14.0,25.0,50.0,ISP,BWI
17,2008,1,3,WN,47.0,87.0,143.0,ISP,FLL
18,2008,1,3,WN,4.0,29.0,155.0,ISP,FLL
19,2008,1,3,WN,64.0,82.0,134.0,ISP,MCO

df_nova1=df_nova[:1000000]


df_nova2 =df_nova[1000000:]

with pd.ExcelWriter('retrassos_simple.xlsx') as writer:  

    df_nova1.to_excel(writer, sheet_name='fulla1_1')

    df_nova2.to_excel(writer, sheet_name='fulla2_2')

#### Creació de dues noves columnes amb xifres simplificades cada 5 minuts

In [11]:
df_nova['ArrDelay5'] = np.floor(df_nova['ArrDelay'] / 5) * 5
df_nova['DepDelay5'] = np.floor(df_nova['DepDelay'] / 5) * 5
df_nova

,Year,Month,DayofMonth,UniqueCarrier,ArrDelay,DepDelay,AirTime,Origin,Dest,ArrDelay5,DepDelay5
0,2008,1,3,WN,-14.0,8.0,116.0,IAD,TPA,-15.0,5.0
1,2008,1,3,WN,2.0,19.0,113.0,IAD,TPA,0.0,15.0
2,2008,1,3,WN,14.0,8.0,76.0,IND,BWI,10.0,5.0
3,2008,1,3,WN,34.0,34.0,77.0,IND,BWI,30.0,30.0
4,2008,1,3,WN,11.0,25.0,87.0,IND,JAX,10.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...
1936753,2008,12,13,DL,25.0,30.0,120.0,MSP,ATL,25.0,30.0
1936754,2008,12,13,DL,75.0,57.0,78.0,RIC,ATL,75.0,55.0
1936755,2008,12,13,DL,99.0,80.0,122.0,ATL,IAH,95.0,80.0
1936756,2008,12,13,DL,9.0,11.0,89.0,IAD,ATL,5.0,10.0
1936757,2008,12,13,DL,-5.0,7.0,104.0,SAT,ATL,-5.0,5.0

In [13]:
df_nova['ArrDelay'].nunique()

1128

In [14]:

df_nova['ArrDelay5'].nunique()

293

In [15]:
df_nova.to_csv("dbsimple.csv")